# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quilt_device_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quilt_device_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import quilt_device_pairing_pb2 as quilt__device__pairing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19quilt_device_config.proto\x12\x12\x63ore.protos.common\x1a\x1aquilt_device_pairing.proto\"(\n&GetSupportedDeviceConfigVersionRequest\":\n\'GetSupportedDeviceConfigVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\x05\"\x1b\n\x19GetWifiScanResultsRequest2\x94\x03\n\x1a\x44\x65viceConfigurationService\x12\x9a\x01\n\x1fGetSupportedDeviceConfigVersion\x12:.core.protos.common.GetSupportedDeviceConfigVersionRequest\x1a;.core.protos.common.GetSupportedDeviceConfigVersionResponse\x12\x63\n\x12GetWifiScanResults\x12-.core.protos.common.GetWifiScanResultsRequest\x1a\x1e.quilt.pairing.v1.WifiScanList\x12t\n\x17SendDeviceConfigRequest\x12,.quilt.pairing.v1.DeviceConfigurationRequest\x1a+.quilt.pairing.v1.DeviceConfigurationResultB \n\x16\x63om.quilt.proto.common\xba\x02\x05Quiltb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quilt_device_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.quilt.proto.common\272\002\005Quilt'
  _globals['_GETSUPPORTEDDEVICECONFIGVERSIONREQUEST']._serialized_start=77
  _globals['_GETSUPPORTEDDEVICECONFIGVERSIONREQUEST']._serialized_end=117
  _globals['_GETSUPPORTEDDEVICECONFIGVERSIONRESPONSE']._serialized_start=119
  _globals['_GETSUPPORTEDDEVICECONFIGVERSIONRESPONSE']._serialized_end=177
  _globals['_GETWIFISCANRESULTSREQUEST']._serialized_start=179
  _globals['_GETWIFISCANRESULTSREQUEST']._serialized_end=206
  _globals['_DEVICECONFIGURATIONSERVICE']._serialized_start=209
  _globals['_DEVICECONFIGURATIONSERVICE']._serialized_end=613
# @@protoc_insertion_point(module_scope)
