# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quilt_system.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quilt_system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12quilt_system.proto\x12\x12\x63ore.protos.system\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n\x13\x43reateSystemRequest\"\x1e\n\x10GetSystemRequest\x12\n\n\x02id\x18\x01 \x01(\t\"A\n\x13UpdateSystemRequest\x12*\n\x06system\x18\x01 \x01(\x0b\x32\x1a.core.protos.system.System\"!\n\x13\x44\x65leteSystemRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12ListSystemsRequest\"B\n\x13ListSystemsResponse\x12+\n\x07systems\x18\x01 \x03(\x0b\x32\x1a.core.protos.system.System\"D\n\x06System\x12\n\n\x02id\x18\x01 \x01(\t\x12.\n\ncreated_ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xb9\x03\n\rSystemService\x12M\n\tGetSystem\x12$.core.protos.system.GetSystemRequest\x1a\x1a.core.protos.system.System\x12S\n\x0c\x43reateSystem\x12\'.core.protos.system.CreateSystemRequest\x1a\x1a.core.protos.system.System\x12S\n\x0cUpdateSystem\x12\'.core.protos.system.UpdateSystemRequest\x1a\x1a.core.protos.system.System\x12O\n\x0c\x44\x65leteSystem\x12\'.core.protos.system.DeleteSystemRequest\x1a\x16.google.protobuf.Empty\x12^\n\x0bListSystems\x12&.core.protos.system.ListSystemsRequest\x1a\'.core.protos.system.ListSystemsResponseB \n\x16\x63om.quilt.proto.system\xba\x02\x05Quiltb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quilt_system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.quilt.proto.system\272\002\005Quilt'
  _globals['_CREATESYSTEMREQUEST']._serialized_start=104
  _globals['_CREATESYSTEMREQUEST']._serialized_end=125
  _globals['_GETSYSTEMREQUEST']._serialized_start=127
  _globals['_GETSYSTEMREQUEST']._serialized_end=157
  _globals['_UPDATESYSTEMREQUEST']._serialized_start=159
  _globals['_UPDATESYSTEMREQUEST']._serialized_end=224
  _globals['_DELETESYSTEMREQUEST']._serialized_start=226
  _globals['_DELETESYSTEMREQUEST']._serialized_end=259
  _globals['_LISTSYSTEMSREQUEST']._serialized_start=261
  _globals['_LISTSYSTEMSREQUEST']._serialized_end=281
  _globals['_LISTSYSTEMSRESPONSE']._serialized_start=283
  _globals['_LISTSYSTEMSRESPONSE']._serialized_end=349
  _globals['_SYSTEM']._serialized_start=351
  _globals['_SYSTEM']._serialized_end=419
  _globals['_SYSTEMSERVICE']._serialized_start=422
  _globals['_SYSTEMSERVICE']._serialized_end=863
# @@protoc_insertion_point(module_scope)
