"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
quilt_system.proto
SystemService lives in package core.protos.system on the wire path.

Wire-confirmed RPCs:
  - CreateSystem
  - DeleteSystem

Additional RPCs present in service definition:
  - GetSystem
  - UpdateSystem
  - ListSystems
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateSystemRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateSystemRequest: _TypeAlias = CreateSystemRequest  # noqa: Y015

@_typing.final
class GetSystemRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSystemRequest: _TypeAlias = GetSystemRequest  # noqa: Y015

@_typing.final
class UpdateSystemRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYSTEM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def system(self) -> Global___System: ...
    def __init__(
        self,
        *,
        system: Global___System | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["system", b"system"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["system", b"system"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateSystemRequest: _TypeAlias = UpdateSystemRequest  # noqa: Y015

@_typing.final
class DeleteSystemRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteSystemRequest: _TypeAlias = DeleteSystemRequest  # noqa: Y015

@_typing.final
class ListSystemsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListSystemsRequest: _TypeAlias = ListSystemsRequest  # noqa: Y015

@_typing.final
class ListSystemsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYSTEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def systems(self) -> _containers.RepeatedCompositeFieldContainer[Global___System]: ...
    def __init__(
        self,
        *,
        systems: _abc.Iterable[Global___System] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["systems", b"systems"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListSystemsResponse: _TypeAlias = ListSystemsResponse  # noqa: Y015

@_typing.final
class System(_message.Message):
    """Simplified System model (id + created timestamp)."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    CREATED_TS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    @_builtins.property
    def created_ts(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        created_ts: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_ts", b"created_ts"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_ts", b"created_ts", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___System: _TypeAlias = System  # noqa: Y015
