"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
quilt_device_pairing.proto
BLE/WiFi device pairing protocol — serialized over Bluetooth (not gRPC).
Used during initial setup of Quilt Smart Module (QSM) and Controller devices.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _WifiSecurityType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _WifiSecurityTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_WifiSecurityType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    WIFI_SECURITY_TYPE_UNKNOWN: _WifiSecurityType.ValueType  # 0
    WIFI_SECURITY_TYPE_NONE: _WifiSecurityType.ValueType  # 1
    WIFI_SECURITY_TYPE_WPAPSK: _WifiSecurityType.ValueType  # 2

class WifiSecurityType(_WifiSecurityType, metaclass=_WifiSecurityTypeEnumTypeWrapper):
    """---------------------------------------------------------------------------
    Enums
    ---------------------------------------------------------------------------
    """

WIFI_SECURITY_TYPE_UNKNOWN: WifiSecurityType.ValueType  # 0
WIFI_SECURITY_TYPE_NONE: WifiSecurityType.ValueType  # 1
WIFI_SECURITY_TYPE_WPAPSK: WifiSecurityType.ValueType  # 2
Global___WifiSecurityType: _TypeAlias = WifiSecurityType  # noqa: Y015

class _DeviceType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DeviceTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DeviceType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DEVICE_TYPE_UNKNOWN: _DeviceType.ValueType  # 0
    DEVICE_TYPE_QUILT_SMART_MODULE: _DeviceType.ValueType  # 1
    DEVICE_TYPE_INDOOR_UNIT: _DeviceType.ValueType  # 2
    DEVICE_TYPE_OUTDOOR_UNIT: _DeviceType.ValueType  # 3
    DEVICE_TYPE_CLOUD_SERVICE: _DeviceType.ValueType  # 4
    DEVICE_TYPE_CONTROLLER: _DeviceType.ValueType  # 5
    DEVICE_TYPE_IOS: _DeviceType.ValueType  # 6
    DEVICE_TYPE_ANDROID: _DeviceType.ValueType  # 7

class DeviceType(_DeviceType, metaclass=_DeviceTypeEnumTypeWrapper): ...

DEVICE_TYPE_UNKNOWN: DeviceType.ValueType  # 0
DEVICE_TYPE_QUILT_SMART_MODULE: DeviceType.ValueType  # 1
DEVICE_TYPE_INDOOR_UNIT: DeviceType.ValueType  # 2
DEVICE_TYPE_OUTDOOR_UNIT: DeviceType.ValueType  # 3
DEVICE_TYPE_CLOUD_SERVICE: DeviceType.ValueType  # 4
DEVICE_TYPE_CONTROLLER: DeviceType.ValueType  # 5
DEVICE_TYPE_IOS: DeviceType.ValueType  # 6
DEVICE_TYPE_ANDROID: DeviceType.ValueType  # 7
Global___DeviceType: _TypeAlias = DeviceType  # noqa: Y015

class _DevicePairingStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DevicePairingStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DevicePairingStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DEVICE_PAIRING_STATUS_UNKNOWN: _DevicePairingStatus.ValueType  # 0
    DEVICE_PAIRING_STATUS_IDLE: _DevicePairingStatus.ValueType  # 1
    DEVICE_PAIRING_STATUS_CONNECTING_TO_WIFI: _DevicePairingStatus.ValueType  # 2
    DEVICE_PAIRING_STATUS_CONNECTED_TO_WIFI_SUCCESSFULLY: _DevicePairingStatus.ValueType  # 3
    DEVICE_PAIRING_STATUS_WRONG_PASSPHRASE: _DevicePairingStatus.ValueType  # 4
    DEVICE_PAIRING_STATUS_WRONG_SSID: _DevicePairingStatus.ValueType  # 5
    DEVICE_PAIRING_STATUS_CONNECTED_TO_CLOUD_SUCCESSFULLY: _DevicePairingStatus.ValueType  # 6
    DEVICE_PAIRING_STATUS_ERROR_NO_DEVICE_ID: _DevicePairingStatus.ValueType  # 7
    DEVICE_PAIRING_STATUS_ERROR_NO_SYSTEM_ID: _DevicePairingStatus.ValueType  # 8

class DevicePairingStatus(_DevicePairingStatus, metaclass=_DevicePairingStatusEnumTypeWrapper): ...

DEVICE_PAIRING_STATUS_UNKNOWN: DevicePairingStatus.ValueType  # 0
DEVICE_PAIRING_STATUS_IDLE: DevicePairingStatus.ValueType  # 1
DEVICE_PAIRING_STATUS_CONNECTING_TO_WIFI: DevicePairingStatus.ValueType  # 2
DEVICE_PAIRING_STATUS_CONNECTED_TO_WIFI_SUCCESSFULLY: DevicePairingStatus.ValueType  # 3
DEVICE_PAIRING_STATUS_WRONG_PASSPHRASE: DevicePairingStatus.ValueType  # 4
DEVICE_PAIRING_STATUS_WRONG_SSID: DevicePairingStatus.ValueType  # 5
DEVICE_PAIRING_STATUS_CONNECTED_TO_CLOUD_SUCCESSFULLY: DevicePairingStatus.ValueType  # 6
DEVICE_PAIRING_STATUS_ERROR_NO_DEVICE_ID: DevicePairingStatus.ValueType  # 7
DEVICE_PAIRING_STATUS_ERROR_NO_SYSTEM_ID: DevicePairingStatus.ValueType  # 8
Global___DevicePairingStatus: _TypeAlias = DevicePairingStatus  # noqa: Y015

@_typing.final
class WifiScan(_message.Message):
    """---------------------------------------------------------------------------
    WiFi scan result (device → phone over BLE)
    ---------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAC_ADDRESS_FIELD_NUMBER: _builtins.int
    SSID_FIELD_NUMBER: _builtins.int
    FREQUENCY_FIELD_NUMBER: _builtins.int
    RSSI_FIELD_NUMBER: _builtins.int
    SECURITY_TYPE_FIELD_NUMBER: _builtins.int
    mac_address: _builtins.str
    """Field 4 contains negative dBm values (RSSI); wire-confirmed.
    Note: WifiState (for established connections) is a different message.
    BSSID
    """
    ssid: _builtins.str
    frequency: _builtins.int
    """MHz; >5000 = 5GHz band"""
    rssi: _builtins.int
    """Signal strength in dBm (negative)"""
    security_type: Global___WifiSecurityType.ValueType
    """0=UNKNOWN, 1=OPEN, 2=WPAPSK"""
    def __init__(
        self,
        *,
        mac_address: _builtins.str = ...,
        ssid: _builtins.str = ...,
        frequency: _builtins.int = ...,
        rssi: _builtins.int = ...,
        security_type: Global___WifiSecurityType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["frequency", b"frequency", "mac_address", b"mac_address", "rssi", b"rssi", "security_type", b"security_type", "ssid", b"ssid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WifiScan: _TypeAlias = WifiScan  # noqa: Y015

@_typing.final
class WifiScanList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCANS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def scans(self) -> _containers.RepeatedCompositeFieldContainer[Global___WifiScan]: ...
    def __init__(
        self,
        *,
        scans: _abc.Iterable[Global___WifiScan] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["scans", b"scans"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WifiScanList: _TypeAlias = WifiScanList  # noqa: Y015

@_typing.final
class WifiConfiguration(_message.Message):
    """---------------------------------------------------------------------------
    Device configuration (phone → device over BLE)
    ---------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    SECURITY_TYPE_FIELD_NUMBER: _builtins.int
    SSID_FIELD_NUMBER: _builtins.int
    PASSPHRASE_FIELD_NUMBER: _builtins.int
    security_type: Global___WifiSecurityType.ValueType
    ssid: _builtins.str
    passphrase: _builtins.str
    def __init__(
        self,
        *,
        security_type: Global___WifiSecurityType.ValueType = ...,
        ssid: _builtins.str = ...,
        passphrase: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["passphrase", b"passphrase", "security_type", b"security_type", "ssid", b"ssid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WifiConfiguration: _TypeAlias = WifiConfiguration  # noqa: Y015

@_typing.final
class DeviceConfiguration(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    DEVICE_UUID_FIELD_NUMBER: _builtins.int
    DEVICE_TYPE_FIELD_NUMBER: _builtins.int
    CLOUD_HOSTNAME_FIELD_NUMBER: _builtins.int
    TOKEN_HOSTNAME_FIELD_NUMBER: _builtins.int
    CLOUD_HOST_PORT_FIELD_NUMBER: _builtins.int
    TOKEN_HOST_PORT_FIELD_NUMBER: _builtins.int
    WIFI_CONFIGS_FIELD_NUMBER: _builtins.int
    SPACE_ID_FIELD_NUMBER: _builtins.int
    SYSTEM_ID_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    device_uuid: _builtins.str
    """empty during pairing; device self-assigns"""
    device_type: Global___DeviceType.ValueType
    cloud_hostname: _builtins.str
    """e.g. "api.prod.quilt.cloud" """
    token_hostname: _builtins.str
    """e.g. "token.prod.quilt.cloud" """
    cloud_host_port: _builtins.int
    """443"""
    token_host_port: _builtins.int
    space_id: _builtins.str
    system_id: _builtins.str
    """system UUID from HDS"""
    @_builtins.property
    def wifi_configs(self) -> _containers.RepeatedCompositeFieldContainer[Global___WifiConfiguration]: ...
    def __init__(
        self,
        *,
        version: _builtins.int = ...,
        device_uuid: _builtins.str = ...,
        device_type: Global___DeviceType.ValueType = ...,
        cloud_hostname: _builtins.str = ...,
        token_hostname: _builtins.str = ...,
        cloud_host_port: _builtins.int = ...,
        token_host_port: _builtins.int = ...,
        wifi_configs: _abc.Iterable[Global___WifiConfiguration] | None = ...,
        space_id: _builtins.str = ...,
        system_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cloud_host_port", b"cloud_host_port", "cloud_hostname", b"cloud_hostname", "device_type", b"device_type", "device_uuid", b"device_uuid", "space_id", b"space_id", "system_id", b"system_id", "token_host_port", b"token_host_port", "token_hostname", b"token_hostname", "version", b"version", "wifi_configs", b"wifi_configs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceConfiguration: _TypeAlias = DeviceConfiguration  # noqa: Y015

@_typing.final
class DeviceConfigurationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_TIMESTAMP_FIELD_NUMBER: _builtins.int
    DEVICE_CONFIGURATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def request_timestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def device_configuration(self) -> Global___DeviceConfiguration: ...
    def __init__(
        self,
        *,
        request_timestamp: _timestamp_pb2.Timestamp | None = ...,
        device_configuration: Global___DeviceConfiguration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device_configuration", b"device_configuration", "request_timestamp", b"request_timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_configuration", b"device_configuration", "request_timestamp", b"request_timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceConfigurationRequest: _TypeAlias = DeviceConfigurationRequest  # noqa: Y015

@_typing.final
class DevicePairingStatusResponse(_message.Message):
    """---------------------------------------------------------------------------
    Pairing status (device → phone over BLE)
    ---------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    status: Global___DevicePairingStatus.ValueType
    def __init__(
        self,
        *,
        status: Global___DevicePairingStatus.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DevicePairingStatusResponse: _TypeAlias = DevicePairingStatusResponse  # noqa: Y015

@_typing.final
class DeviceConfigurationResult(_message.Message):
    """Response from SendDeviceConfigRequest (WiFi gRPC provisioning)"""

    DESCRIPTOR: _descriptor.Descriptor

    IS_DEVICE_CONFIGURED_FIELD_NUMBER: _builtins.int
    is_device_configured: _builtins.bool
    def __init__(
        self,
        *,
        is_device_configured: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_device_configured", b"is_device_configured"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceConfigurationResult: _TypeAlias = DeviceConfigurationResult  # noqa: Y015
