# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import quilt_hds_pb2 as quilt__hds__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quilt_hds_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HomeDatastoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHomeDatastoreSystem = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetHomeDatastoreSystem',
                request_serializer=quilt__hds__pb2.GetHomeDatastoreSystemRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.HomeDatastoreSystem.FromString,
                _registered_method=True)
        self.GetSpace = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetSpace',
                request_serializer=quilt__hds__pb2.GetSpaceRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.Space.FromString,
                _registered_method=True)
        self.CreateSpace = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/CreateSpace',
                request_serializer=quilt__hds__pb2.CreateSpaceRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.Space.FromString,
                _registered_method=True)
        self.UpdateSpace = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateSpace',
                request_serializer=quilt__hds__pb2.UpdateSpaceRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.Space.FromString,
                _registered_method=True)
        self.DeleteSpace = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteSpace',
                request_serializer=quilt__hds__pb2.DeleteSpaceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateIndoorUnit = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateIndoorUnit',
                request_serializer=quilt__hds__pb2.UpdateIndoorUnitRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.IndoorUnit.FromString,
                _registered_method=True)
        self.DeleteIndoorUnit = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteIndoorUnit',
                request_serializer=quilt__hds__pb2.DeleteIndoorUnitRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetIndoorUnitHardware = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetIndoorUnitHardware',
                request_serializer=quilt__hds__pb2.GetIndoorUnitHardwareRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.IndoorUnitHardware.FromString,
                _registered_method=True)
        self.GetQuiltSmartModule = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetQuiltSmartModule',
                request_serializer=quilt__hds__pb2.GetQuiltSmartModuleRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.QuiltSmartModule.FromString,
                _registered_method=True)
        self.UpdateController = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateController',
                request_serializer=quilt__hds__pb2.UpdateControllerRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.Controller.FromString,
                _registered_method=True)
        self.DeleteController = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteController',
                request_serializer=quilt__hds__pb2.DeleteControllerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetControllerHardware = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetControllerHardware',
                request_serializer=quilt__hds__pb2.GetControllerHardwareRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ControllerHardware.FromString,
                _registered_method=True)
        self.DeleteOutdoorUnit = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteOutdoorUnit',
                request_serializer=quilt__hds__pb2.DeleteOutdoorUnitRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateRemoteSensor = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/CreateRemoteSensor',
                request_serializer=quilt__hds__pb2.CreateRemoteSensorRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.RemoteSensor.FromString,
                _registered_method=True)
        self.UpdateRemoteSensor = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateRemoteSensor',
                request_serializer=quilt__hds__pb2.UpdateRemoteSensorRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.RemoteSensor.FromString,
                _registered_method=True)
        self.DeleteRemoteSensor = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteRemoteSensor',
                request_serializer=quilt__hds__pb2.DeleteRemoteSensorRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateControllerRemoteSensor = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/CreateControllerRemoteSensor',
                request_serializer=quilt__hds__pb2.CreateControllerRemoteSensorRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ControllerRemoteSensor.FromString,
                _registered_method=True)
        self.UpdateControllerRemoteSensor = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateControllerRemoteSensor',
                request_serializer=quilt__hds__pb2.UpdateControllerRemoteSensorRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ControllerRemoteSensor.FromString,
                _registered_method=True)
        self.DeleteControllerRemoteSensor = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteControllerRemoteSensor',
                request_serializer=quilt__hds__pb2.DeleteControllerRemoteSensorRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateScheduleDay = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/CreateScheduleDay',
                request_serializer=quilt__hds__pb2.CreateScheduleDayRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ScheduleDay.FromString,
                _registered_method=True)
        self.GetScheduleDay = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetScheduleDay',
                request_serializer=quilt__hds__pb2.GetScheduleDayRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ScheduleDay.FromString,
                _registered_method=True)
        self.UpdateScheduleDay = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateScheduleDay',
                request_serializer=quilt__hds__pb2.UpdateScheduleDayRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ScheduleDay.FromString,
                _registered_method=True)
        self.DeleteScheduleDay = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteScheduleDay',
                request_serializer=quilt__hds__pb2.DeleteScheduleDayRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListScheduleDays = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/ListScheduleDays',
                request_serializer=quilt__hds__pb2.ListScheduleDaysRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ListScheduleDaysResponse.FromString,
                _registered_method=True)
        self.CreateScheduleWeek = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/CreateScheduleWeek',
                request_serializer=quilt__hds__pb2.CreateScheduleWeekRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ScheduleWeek.FromString,
                _registered_method=True)
        self.GetScheduleWeek = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetScheduleWeek',
                request_serializer=quilt__hds__pb2.GetScheduleWeekRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ScheduleWeek.FromString,
                _registered_method=True)
        self.UpdateScheduleWeek = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateScheduleWeek',
                request_serializer=quilt__hds__pb2.UpdateScheduleWeekRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ScheduleWeek.FromString,
                _registered_method=True)
        self.DeleteScheduleWeek = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteScheduleWeek',
                request_serializer=quilt__hds__pb2.DeleteScheduleWeekRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListScheduleWeeks = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/ListScheduleWeeks',
                request_serializer=quilt__hds__pb2.ListScheduleWeeksRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ListScheduleWeeksResponse.FromString,
                _registered_method=True)
        self.CreateComfortSetting = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/CreateComfortSetting',
                request_serializer=quilt__hds__pb2.CreateComfortSettingRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ComfortSetting.FromString,
                _registered_method=True)
        self.GetComfortSetting = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetComfortSetting',
                request_serializer=quilt__hds__pb2.GetComfortSettingRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ComfortSetting.FromString,
                _registered_method=True)
        self.UpdateComfortSetting = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateComfortSetting',
                request_serializer=quilt__hds__pb2.UpdateComfortSettingRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ComfortSetting.FromString,
                _registered_method=True)
        self.DeleteComfortSetting = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteComfortSetting',
                request_serializer=quilt__hds__pb2.DeleteComfortSettingRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListComfortSettings = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/ListComfortSettings',
                request_serializer=quilt__hds__pb2.ListComfortSettingsRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ListComfortSettingsResponse.FromString,
                _registered_method=True)
        self.CreateLocation = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/CreateLocation',
                request_serializer=quilt__hds__pb2.CreateLocationRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.Location.FromString,
                _registered_method=True)
        self.GetLocation = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetLocation',
                request_serializer=quilt__hds__pb2.GetLocationRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.Location.FromString,
                _registered_method=True)
        self.UpdateLocation = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateLocation',
                request_serializer=quilt__hds__pb2.UpdateLocationRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.Location.FromString,
                _registered_method=True)
        self.DeleteLocation = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/DeleteLocation',
                request_serializer=quilt__hds__pb2.DeleteLocationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListLocations = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/ListLocations',
                request_serializer=quilt__hds__pb2.ListLocationsRequest.SerializeToString,
                response_deserializer=quilt__hds__pb2.ListLocationsResponse.FromString,
                _registered_method=True)


class HomeDatastoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHomeDatastoreSystem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSpace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSpace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSpace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIndoorUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIndoorUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndoorUnitHardware(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuiltSmartModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateController(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteController(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControllerHardware(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOutdoorUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRemoteSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRemoteSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRemoteSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateControllerRemoteSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateControllerRemoteSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteControllerRemoteSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateScheduleDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateScheduleDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScheduleDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScheduleDays(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateScheduleWeek(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleWeek(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateScheduleWeek(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScheduleWeek(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScheduleWeeks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComfortSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComfortSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComfortSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteComfortSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListComfortSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HomeDatastoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHomeDatastoreSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHomeDatastoreSystem,
                    request_deserializer=quilt__hds__pb2.GetHomeDatastoreSystemRequest.FromString,
                    response_serializer=quilt__hds__pb2.HomeDatastoreSystem.SerializeToString,
            ),
            'GetSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpace,
                    request_deserializer=quilt__hds__pb2.GetSpaceRequest.FromString,
                    response_serializer=quilt__hds__pb2.Space.SerializeToString,
            ),
            'CreateSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSpace,
                    request_deserializer=quilt__hds__pb2.CreateSpaceRequest.FromString,
                    response_serializer=quilt__hds__pb2.Space.SerializeToString,
            ),
            'UpdateSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSpace,
                    request_deserializer=quilt__hds__pb2.UpdateSpaceRequest.FromString,
                    response_serializer=quilt__hds__pb2.Space.SerializeToString,
            ),
            'DeleteSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSpace,
                    request_deserializer=quilt__hds__pb2.DeleteSpaceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateIndoorUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIndoorUnit,
                    request_deserializer=quilt__hds__pb2.UpdateIndoorUnitRequest.FromString,
                    response_serializer=quilt__hds__pb2.IndoorUnit.SerializeToString,
            ),
            'DeleteIndoorUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIndoorUnit,
                    request_deserializer=quilt__hds__pb2.DeleteIndoorUnitRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetIndoorUnitHardware': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndoorUnitHardware,
                    request_deserializer=quilt__hds__pb2.GetIndoorUnitHardwareRequest.FromString,
                    response_serializer=quilt__hds__pb2.IndoorUnitHardware.SerializeToString,
            ),
            'GetQuiltSmartModule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuiltSmartModule,
                    request_deserializer=quilt__hds__pb2.GetQuiltSmartModuleRequest.FromString,
                    response_serializer=quilt__hds__pb2.QuiltSmartModule.SerializeToString,
            ),
            'UpdateController': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateController,
                    request_deserializer=quilt__hds__pb2.UpdateControllerRequest.FromString,
                    response_serializer=quilt__hds__pb2.Controller.SerializeToString,
            ),
            'DeleteController': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteController,
                    request_deserializer=quilt__hds__pb2.DeleteControllerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetControllerHardware': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControllerHardware,
                    request_deserializer=quilt__hds__pb2.GetControllerHardwareRequest.FromString,
                    response_serializer=quilt__hds__pb2.ControllerHardware.SerializeToString,
            ),
            'DeleteOutdoorUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOutdoorUnit,
                    request_deserializer=quilt__hds__pb2.DeleteOutdoorUnitRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateRemoteSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRemoteSensor,
                    request_deserializer=quilt__hds__pb2.CreateRemoteSensorRequest.FromString,
                    response_serializer=quilt__hds__pb2.RemoteSensor.SerializeToString,
            ),
            'UpdateRemoteSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRemoteSensor,
                    request_deserializer=quilt__hds__pb2.UpdateRemoteSensorRequest.FromString,
                    response_serializer=quilt__hds__pb2.RemoteSensor.SerializeToString,
            ),
            'DeleteRemoteSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRemoteSensor,
                    request_deserializer=quilt__hds__pb2.DeleteRemoteSensorRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateControllerRemoteSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateControllerRemoteSensor,
                    request_deserializer=quilt__hds__pb2.CreateControllerRemoteSensorRequest.FromString,
                    response_serializer=quilt__hds__pb2.ControllerRemoteSensor.SerializeToString,
            ),
            'UpdateControllerRemoteSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateControllerRemoteSensor,
                    request_deserializer=quilt__hds__pb2.UpdateControllerRemoteSensorRequest.FromString,
                    response_serializer=quilt__hds__pb2.ControllerRemoteSensor.SerializeToString,
            ),
            'DeleteControllerRemoteSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteControllerRemoteSensor,
                    request_deserializer=quilt__hds__pb2.DeleteControllerRemoteSensorRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateScheduleDay': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateScheduleDay,
                    request_deserializer=quilt__hds__pb2.CreateScheduleDayRequest.FromString,
                    response_serializer=quilt__hds__pb2.ScheduleDay.SerializeToString,
            ),
            'GetScheduleDay': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleDay,
                    request_deserializer=quilt__hds__pb2.GetScheduleDayRequest.FromString,
                    response_serializer=quilt__hds__pb2.ScheduleDay.SerializeToString,
            ),
            'UpdateScheduleDay': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateScheduleDay,
                    request_deserializer=quilt__hds__pb2.UpdateScheduleDayRequest.FromString,
                    response_serializer=quilt__hds__pb2.ScheduleDay.SerializeToString,
            ),
            'DeleteScheduleDay': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScheduleDay,
                    request_deserializer=quilt__hds__pb2.DeleteScheduleDayRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListScheduleDays': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScheduleDays,
                    request_deserializer=quilt__hds__pb2.ListScheduleDaysRequest.FromString,
                    response_serializer=quilt__hds__pb2.ListScheduleDaysResponse.SerializeToString,
            ),
            'CreateScheduleWeek': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateScheduleWeek,
                    request_deserializer=quilt__hds__pb2.CreateScheduleWeekRequest.FromString,
                    response_serializer=quilt__hds__pb2.ScheduleWeek.SerializeToString,
            ),
            'GetScheduleWeek': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleWeek,
                    request_deserializer=quilt__hds__pb2.GetScheduleWeekRequest.FromString,
                    response_serializer=quilt__hds__pb2.ScheduleWeek.SerializeToString,
            ),
            'UpdateScheduleWeek': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateScheduleWeek,
                    request_deserializer=quilt__hds__pb2.UpdateScheduleWeekRequest.FromString,
                    response_serializer=quilt__hds__pb2.ScheduleWeek.SerializeToString,
            ),
            'DeleteScheduleWeek': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScheduleWeek,
                    request_deserializer=quilt__hds__pb2.DeleteScheduleWeekRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListScheduleWeeks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScheduleWeeks,
                    request_deserializer=quilt__hds__pb2.ListScheduleWeeksRequest.FromString,
                    response_serializer=quilt__hds__pb2.ListScheduleWeeksResponse.SerializeToString,
            ),
            'CreateComfortSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComfortSetting,
                    request_deserializer=quilt__hds__pb2.CreateComfortSettingRequest.FromString,
                    response_serializer=quilt__hds__pb2.ComfortSetting.SerializeToString,
            ),
            'GetComfortSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComfortSetting,
                    request_deserializer=quilt__hds__pb2.GetComfortSettingRequest.FromString,
                    response_serializer=quilt__hds__pb2.ComfortSetting.SerializeToString,
            ),
            'UpdateComfortSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComfortSetting,
                    request_deserializer=quilt__hds__pb2.UpdateComfortSettingRequest.FromString,
                    response_serializer=quilt__hds__pb2.ComfortSetting.SerializeToString,
            ),
            'DeleteComfortSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteComfortSetting,
                    request_deserializer=quilt__hds__pb2.DeleteComfortSettingRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListComfortSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListComfortSettings,
                    request_deserializer=quilt__hds__pb2.ListComfortSettingsRequest.FromString,
                    response_serializer=quilt__hds__pb2.ListComfortSettingsResponse.SerializeToString,
            ),
            'CreateLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLocation,
                    request_deserializer=quilt__hds__pb2.CreateLocationRequest.FromString,
                    response_serializer=quilt__hds__pb2.Location.SerializeToString,
            ),
            'GetLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocation,
                    request_deserializer=quilt__hds__pb2.GetLocationRequest.FromString,
                    response_serializer=quilt__hds__pb2.Location.SerializeToString,
            ),
            'UpdateLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLocation,
                    request_deserializer=quilt__hds__pb2.UpdateLocationRequest.FromString,
                    response_serializer=quilt__hds__pb2.Location.SerializeToString,
            ),
            'DeleteLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLocation,
                    request_deserializer=quilt__hds__pb2.DeleteLocationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLocations,
                    request_deserializer=quilt__hds__pb2.ListLocationsRequest.FromString,
                    response_serializer=quilt__hds__pb2.ListLocationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.protos.home_datastore.HomeDatastoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.protos.home_datastore.HomeDatastoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HomeDatastoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHomeDatastoreSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetHomeDatastoreSystem',
            quilt__hds__pb2.GetHomeDatastoreSystemRequest.SerializeToString,
            quilt__hds__pb2.HomeDatastoreSystem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetSpace',
            quilt__hds__pb2.GetSpaceRequest.SerializeToString,
            quilt__hds__pb2.Space.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/CreateSpace',
            quilt__hds__pb2.CreateSpaceRequest.SerializeToString,
            quilt__hds__pb2.Space.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateSpace',
            quilt__hds__pb2.UpdateSpaceRequest.SerializeToString,
            quilt__hds__pb2.Space.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteSpace',
            quilt__hds__pb2.DeleteSpaceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIndoorUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateIndoorUnit',
            quilt__hds__pb2.UpdateIndoorUnitRequest.SerializeToString,
            quilt__hds__pb2.IndoorUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIndoorUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteIndoorUnit',
            quilt__hds__pb2.DeleteIndoorUnitRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndoorUnitHardware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetIndoorUnitHardware',
            quilt__hds__pb2.GetIndoorUnitHardwareRequest.SerializeToString,
            quilt__hds__pb2.IndoorUnitHardware.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuiltSmartModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetQuiltSmartModule',
            quilt__hds__pb2.GetQuiltSmartModuleRequest.SerializeToString,
            quilt__hds__pb2.QuiltSmartModule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateController',
            quilt__hds__pb2.UpdateControllerRequest.SerializeToString,
            quilt__hds__pb2.Controller.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteController',
            quilt__hds__pb2.DeleteControllerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControllerHardware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetControllerHardware',
            quilt__hds__pb2.GetControllerHardwareRequest.SerializeToString,
            quilt__hds__pb2.ControllerHardware.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOutdoorUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteOutdoorUnit',
            quilt__hds__pb2.DeleteOutdoorUnitRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRemoteSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/CreateRemoteSensor',
            quilt__hds__pb2.CreateRemoteSensorRequest.SerializeToString,
            quilt__hds__pb2.RemoteSensor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRemoteSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateRemoteSensor',
            quilt__hds__pb2.UpdateRemoteSensorRequest.SerializeToString,
            quilt__hds__pb2.RemoteSensor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRemoteSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteRemoteSensor',
            quilt__hds__pb2.DeleteRemoteSensorRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateControllerRemoteSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/CreateControllerRemoteSensor',
            quilt__hds__pb2.CreateControllerRemoteSensorRequest.SerializeToString,
            quilt__hds__pb2.ControllerRemoteSensor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateControllerRemoteSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateControllerRemoteSensor',
            quilt__hds__pb2.UpdateControllerRemoteSensorRequest.SerializeToString,
            quilt__hds__pb2.ControllerRemoteSensor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteControllerRemoteSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteControllerRemoteSensor',
            quilt__hds__pb2.DeleteControllerRemoteSensorRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateScheduleDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/CreateScheduleDay',
            quilt__hds__pb2.CreateScheduleDayRequest.SerializeToString,
            quilt__hds__pb2.ScheduleDay.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetScheduleDay',
            quilt__hds__pb2.GetScheduleDayRequest.SerializeToString,
            quilt__hds__pb2.ScheduleDay.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateScheduleDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateScheduleDay',
            quilt__hds__pb2.UpdateScheduleDayRequest.SerializeToString,
            quilt__hds__pb2.ScheduleDay.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteScheduleDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteScheduleDay',
            quilt__hds__pb2.DeleteScheduleDayRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScheduleDays(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/ListScheduleDays',
            quilt__hds__pb2.ListScheduleDaysRequest.SerializeToString,
            quilt__hds__pb2.ListScheduleDaysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateScheduleWeek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/CreateScheduleWeek',
            quilt__hds__pb2.CreateScheduleWeekRequest.SerializeToString,
            quilt__hds__pb2.ScheduleWeek.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleWeek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetScheduleWeek',
            quilt__hds__pb2.GetScheduleWeekRequest.SerializeToString,
            quilt__hds__pb2.ScheduleWeek.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateScheduleWeek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateScheduleWeek',
            quilt__hds__pb2.UpdateScheduleWeekRequest.SerializeToString,
            quilt__hds__pb2.ScheduleWeek.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteScheduleWeek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteScheduleWeek',
            quilt__hds__pb2.DeleteScheduleWeekRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScheduleWeeks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/ListScheduleWeeks',
            quilt__hds__pb2.ListScheduleWeeksRequest.SerializeToString,
            quilt__hds__pb2.ListScheduleWeeksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateComfortSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/CreateComfortSetting',
            quilt__hds__pb2.CreateComfortSettingRequest.SerializeToString,
            quilt__hds__pb2.ComfortSetting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComfortSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetComfortSetting',
            quilt__hds__pb2.GetComfortSettingRequest.SerializeToString,
            quilt__hds__pb2.ComfortSetting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateComfortSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateComfortSetting',
            quilt__hds__pb2.UpdateComfortSettingRequest.SerializeToString,
            quilt__hds__pb2.ComfortSetting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteComfortSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteComfortSetting',
            quilt__hds__pb2.DeleteComfortSettingRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListComfortSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/ListComfortSettings',
            quilt__hds__pb2.ListComfortSettingsRequest.SerializeToString,
            quilt__hds__pb2.ListComfortSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/CreateLocation',
            quilt__hds__pb2.CreateLocationRequest.SerializeToString,
            quilt__hds__pb2.Location.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetLocation',
            quilt__hds__pb2.GetLocationRequest.SerializeToString,
            quilt__hds__pb2.Location.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateLocation',
            quilt__hds__pb2.UpdateLocationRequest.SerializeToString,
            quilt__hds__pb2.Location.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/DeleteLocation',
            quilt__hds__pb2.DeleteLocationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/ListLocations',
            quilt__hds__pb2.ListLocationsRequest.SerializeToString,
            quilt__hds__pb2.ListLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
