"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
quilt_device_config.proto
DeviceConfigurationService — plaintext gRPC provisioning API a QSM/Dial exposes on port 50051
while in setup mode (169.254.1.1 on its provisioning hotspot).
Wire path: /core.protos.common.DeviceConfigurationService/<Method>.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetSupportedDeviceConfigVersionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSupportedDeviceConfigVersionRequest: _TypeAlias = GetSupportedDeviceConfigVersionRequest  # noqa: Y015

@_typing.final
class GetSupportedDeviceConfigVersionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    def __init__(
        self,
        *,
        version: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSupportedDeviceConfigVersionResponse: _TypeAlias = GetSupportedDeviceConfigVersionResponse  # noqa: Y015

@_typing.final
class GetWifiScanResultsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetWifiScanResultsRequest: _TypeAlias = GetWifiScanResultsRequest  # noqa: Y015
