"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
quilt_system.proto
SystemService lives in package core.protos.system on the wire path. Its only RPC is
DeleteSystem; systems are created via MobileAppService/CreateAndConfigureSystem.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import quilt_hds_pb2 as _quilt_hds_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SystemField2(_message.Message):
    """Shape decoded live from GetSystem/ListSystems (2026-10-05). The names of fields 2 and 3 are
    unknown: both were empty for every system observed; the human-readable system name comes
    from SystemInformationService/ListSystems instead.
    """

    DESCRIPTOR: _descriptor.Descriptor

    FIELD_1_FIELD_NUMBER: _builtins.int
    field_1: _builtins.str
    def __init__(
        self,
        *,
        field_1: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field_1", b"field_1"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SystemField2: _TypeAlias = SystemField2  # noqa: Y015

@_typing.final
class System(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    FIELD_2_FIELD_NUMBER: _builtins.int
    FIELD_3_FIELD_NUMBER: _builtins.int
    field_3: _builtins.str
    @_builtins.property
    def header(self) -> _quilt_hds_pb2.EntityMetadata:
        """object_id = system id, created_ts"""

    @_builtins.property
    def field_2(self) -> Global___SystemField2: ...
    def __init__(
        self,
        *,
        header: _quilt_hds_pb2.EntityMetadata | None = ...,
        field_2: Global___SystemField2 | None = ...,
        field_3: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["field_2", b"field_2", "header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field_2", b"field_2", "field_3", b"field_3", "header", b"header"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___System: _TypeAlias = System  # noqa: Y015

@_typing.final
class GetSystemRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECT_ID_FIELD_NUMBER: _builtins.int
    object_id: _builtins.str
    def __init__(
        self,
        *,
        object_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["object_id", b"object_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSystemRequest: _TypeAlias = GetSystemRequest  # noqa: Y015

@_typing.final
class CreateSystemRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYSTEM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def system(self) -> Global___System: ...
    def __init__(
        self,
        *,
        system: Global___System | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["system", b"system"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["system", b"system"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateSystemRequest: _TypeAlias = CreateSystemRequest  # noqa: Y015

@_typing.final
class UpdateSystemRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYSTEM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def system(self) -> Global___System: ...
    def __init__(
        self,
        *,
        system: Global___System | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["system", b"system"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["system", b"system"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateSystemRequest: _TypeAlias = UpdateSystemRequest  # noqa: Y015

@_typing.final
class DeleteSystemRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECT_ID_FIELD_NUMBER: _builtins.int
    object_id: _builtins.str
    def __init__(
        self,
        *,
        object_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["object_id", b"object_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteSystemRequest: _TypeAlias = DeleteSystemRequest  # noqa: Y015

@_typing.final
class ListSystemsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FILTER_FIELD_NUMBER: _builtins.int
    filter: _builtins.str
    def __init__(
        self,
        *,
        filter: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListSystemsRequest: _TypeAlias = ListSystemsRequest  # noqa: Y015

@_typing.final
class ListSystemsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYSTEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def systems(self) -> _containers.RepeatedCompositeFieldContainer[Global___System]: ...
    def __init__(
        self,
        *,
        systems: _abc.Iterable[Global___System] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["systems", b"systems"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListSystemsResponse: _TypeAlias = ListSystemsResponse  # noqa: Y015
