# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import quilt_system_pb2 as quilt__system__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quilt_system_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystem = channel.unary_unary(
                '/core.protos.system.SystemService/GetSystem',
                request_serializer=quilt__system__pb2.GetSystemRequest.SerializeToString,
                response_deserializer=quilt__system__pb2.System.FromString,
                _registered_method=True)
        self.CreateSystem = channel.unary_unary(
                '/core.protos.system.SystemService/CreateSystem',
                request_serializer=quilt__system__pb2.CreateSystemRequest.SerializeToString,
                response_deserializer=quilt__system__pb2.System.FromString,
                _registered_method=True)
        self.UpdateSystem = channel.unary_unary(
                '/core.protos.system.SystemService/UpdateSystem',
                request_serializer=quilt__system__pb2.UpdateSystemRequest.SerializeToString,
                response_deserializer=quilt__system__pb2.System.FromString,
                _registered_method=True)
        self.DeleteSystem = channel.unary_unary(
                '/core.protos.system.SystemService/DeleteSystem',
                request_serializer=quilt__system__pb2.DeleteSystemRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListSystems = channel.unary_unary(
                '/core.protos.system.SystemService/ListSystems',
                request_serializer=quilt__system__pb2.ListSystemsRequest.SerializeToString,
                response_deserializer=quilt__system__pb2.ListSystemsResponse.FromString,
                _registered_method=True)


class SystemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSystem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSystem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSystem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSystem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSystems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystem,
                    request_deserializer=quilt__system__pb2.GetSystemRequest.FromString,
                    response_serializer=quilt__system__pb2.System.SerializeToString,
            ),
            'CreateSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSystem,
                    request_deserializer=quilt__system__pb2.CreateSystemRequest.FromString,
                    response_serializer=quilt__system__pb2.System.SerializeToString,
            ),
            'UpdateSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSystem,
                    request_deserializer=quilt__system__pb2.UpdateSystemRequest.FromString,
                    response_serializer=quilt__system__pb2.System.SerializeToString,
            ),
            'DeleteSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSystem,
                    request_deserializer=quilt__system__pb2.DeleteSystemRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListSystems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSystems,
                    request_deserializer=quilt__system__pb2.ListSystemsRequest.FromString,
                    response_serializer=quilt__system__pb2.ListSystemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.protos.system.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.protos.system.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.system.SystemService/GetSystem',
            quilt__system__pb2.GetSystemRequest.SerializeToString,
            quilt__system__pb2.System.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.system.SystemService/CreateSystem',
            quilt__system__pb2.CreateSystemRequest.SerializeToString,
            quilt__system__pb2.System.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.system.SystemService/UpdateSystem',
            quilt__system__pb2.UpdateSystemRequest.SerializeToString,
            quilt__system__pb2.System.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.system.SystemService/DeleteSystem',
            quilt__system__pb2.DeleteSystemRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSystems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.system.SystemService/ListSystems',
            quilt__system__pb2.ListSystemsRequest.SerializeToString,
            quilt__system__pb2.ListSystemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
