"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
quilt_actions.proto
HomeActionService — unified "submit an action" control API.
Wire path: /core.protos.actions.HomeActionService/SubmitAction
Fields marked `optional` have explicit presence: omit them to leave a setting unchanged.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ActionResult:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ActionResultEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ActionResult.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ACTION_RESULT_UNSPECIFIED: _ActionResult.ValueType  # 0
    ACTION_RESULT_SUCCESS: _ActionResult.ValueType  # 1
    ACTION_RESULT_FAILED: _ActionResult.ValueType  # 2
    ACTION_RESULT_PARTIAL_FAILURE: _ActionResult.ValueType  # 3
    """multi-target action applied to only some targets"""

class ActionResult(_ActionResult, metaclass=_ActionResultEnumTypeWrapper): ...

ACTION_RESULT_UNSPECIFIED: ActionResult.ValueType  # 0
ACTION_RESULT_SUCCESS: ActionResult.ValueType  # 1
ACTION_RESULT_FAILED: ActionResult.ValueType  # 2
ACTION_RESULT_PARTIAL_FAILURE: ActionResult.ValueType  # 3
"""multi-target action applied to only some targets"""
Global___ActionResult: _TypeAlias = ActionResult  # noqa: Y015

class _ClientType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ClientTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ClientType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CLIENT_TYPE_UNSPECIFIED: _ClientType.ValueType  # 0
    CLIENT_TYPE_IOS: _ClientType.ValueType  # 1
    CLIENT_TYPE_ANDROID: _ClientType.ValueType  # 2
    CLIENT_TYPE_WEB: _ClientType.ValueType  # 3

class ClientType(_ClientType, metaclass=_ClientTypeEnumTypeWrapper):
    """---------------------------------------------------------------------------
    Source — provenance of the action
    ---------------------------------------------------------------------------
    """

CLIENT_TYPE_UNSPECIFIED: ClientType.ValueType  # 0
CLIENT_TYPE_IOS: ClientType.ValueType  # 1
CLIENT_TYPE_ANDROID: ClientType.ValueType  # 2
CLIENT_TYPE_WEB: ClientType.ValueType  # 3
Global___ClientType: _TypeAlias = ClientType  # noqa: Y015

class _ClimateMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ClimateModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ClimateMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CLIMATE_MODE_UNSPECIFIED: _ClimateMode.ValueType  # 0
    CLIMATE_MODE_OFF: _ClimateMode.ValueType  # 1
    CLIMATE_MODE_HEAT: _ClimateMode.ValueType  # 2
    CLIMATE_MODE_COOL: _ClimateMode.ValueType  # 3
    CLIMATE_MODE_DUAL_SETPOINT: _ClimateMode.ValueType  # 4
    CLIMATE_MODE_FAN: _ClimateMode.ValueType  # 5
    CLIMATE_MODE_DRY: _ClimateMode.ValueType  # 6
    CLIMATE_MODE_AWAY: _ClimateMode.ValueType  # 7

class ClimateMode(_ClimateMode, metaclass=_ClimateModeEnumTypeWrapper):
    """---------------------------------------------------------------------------
    Climate
    ---------------------------------------------------------------------------

    A separate, simplified mode enum — NOT the HDS HVACMode numbering
    (e.g. HVAC_MODE_COOL=2 but CLIMATE_MODE_COOL=3). DUAL_SETPOINT replaces AUTO and
    AWAY is new; there are no FALLBACK_* values.
    """

CLIMATE_MODE_UNSPECIFIED: ClimateMode.ValueType  # 0
CLIMATE_MODE_OFF: ClimateMode.ValueType  # 1
CLIMATE_MODE_HEAT: ClimateMode.ValueType  # 2
CLIMATE_MODE_COOL: ClimateMode.ValueType  # 3
CLIMATE_MODE_DUAL_SETPOINT: ClimateMode.ValueType  # 4
CLIMATE_MODE_FAN: ClimateMode.ValueType  # 5
CLIMATE_MODE_DRY: ClimateMode.ValueType  # 6
CLIMATE_MODE_AWAY: ClimateMode.ValueType  # 7
Global___ClimateMode: _TypeAlias = ClimateMode  # noqa: Y015

class _FanSpeedLevel:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FanSpeedLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FanSpeedLevel.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FAN_SPEED_LEVEL_UNSPECIFIED: _FanSpeedLevel.ValueType  # 0
    FAN_SPEED_LEVEL_AUTO: _FanSpeedLevel.ValueType  # 1
    FAN_SPEED_LEVEL_QUIET: _FanSpeedLevel.ValueType  # 2
    FAN_SPEED_LEVEL_LOW: _FanSpeedLevel.ValueType  # 3
    FAN_SPEED_LEVEL_MEDIUM: _FanSpeedLevel.ValueType  # 4
    FAN_SPEED_LEVEL_HIGH: _FanSpeedLevel.ValueType  # 5
    FAN_SPEED_LEVEL_BLAST: _FanSpeedLevel.ValueType  # 6

class FanSpeedLevel(_FanSpeedLevel, metaclass=_FanSpeedLevelEnumTypeWrapper):
    """Named fan-speed steps instead of the HDS fan_speed_percent float."""

FAN_SPEED_LEVEL_UNSPECIFIED: FanSpeedLevel.ValueType  # 0
FAN_SPEED_LEVEL_AUTO: FanSpeedLevel.ValueType  # 1
FAN_SPEED_LEVEL_QUIET: FanSpeedLevel.ValueType  # 2
FAN_SPEED_LEVEL_LOW: FanSpeedLevel.ValueType  # 3
FAN_SPEED_LEVEL_MEDIUM: FanSpeedLevel.ValueType  # 4
FAN_SPEED_LEVEL_HIGH: FanSpeedLevel.ValueType  # 5
FAN_SPEED_LEVEL_BLAST: FanSpeedLevel.ValueType  # 6
Global___FanSpeedLevel: _TypeAlias = FanSpeedLevel  # noqa: Y015

class _FanAngleLevel:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FanAngleLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FanAngleLevel.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FAN_ANGLE_LEVEL_UNSPECIFIED: _FanAngleLevel.ValueType  # 0
    FAN_ANGLE_LEVEL_AUTO: _FanAngleLevel.ValueType  # 1
    FAN_ANGLE_LEVEL_CEILING: _FanAngleLevel.ValueType  # 2
    FAN_ANGLE_LEVEL_HIGH: _FanAngleLevel.ValueType  # 3
    FAN_ANGLE_LEVEL_MIDDLE: _FanAngleLevel.ValueType  # 4
    FAN_ANGLE_LEVEL_LOW: _FanAngleLevel.ValueType  # 5
    FAN_ANGLE_LEVEL_FLOOR: _FanAngleLevel.ValueType  # 6

class FanAngleLevel(_FanAngleLevel, metaclass=_FanAngleLevelEnumTypeWrapper):
    """Named louver positions instead of the HDS louver_fixed_position float."""

FAN_ANGLE_LEVEL_UNSPECIFIED: FanAngleLevel.ValueType  # 0
FAN_ANGLE_LEVEL_AUTO: FanAngleLevel.ValueType  # 1
FAN_ANGLE_LEVEL_CEILING: FanAngleLevel.ValueType  # 2
FAN_ANGLE_LEVEL_HIGH: FanAngleLevel.ValueType  # 3
FAN_ANGLE_LEVEL_MIDDLE: FanAngleLevel.ValueType  # 4
FAN_ANGLE_LEVEL_LOW: FanAngleLevel.ValueType  # 5
FAN_ANGLE_LEVEL_FLOOR: FanAngleLevel.ValueType  # 6
Global___FanAngleLevel: _TypeAlias = FanAngleLevel  # noqa: Y015

class _LightPower:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LightPowerEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LightPower.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LIGHT_POWER_UNSPECIFIED: _LightPower.ValueType  # 0
    LIGHT_POWER_ON: _LightPower.ValueType  # 1
    LIGHT_POWER_OFF: _LightPower.ValueType  # 2

class LightPower(_LightPower, metaclass=_LightPowerEnumTypeWrapper):
    """---------------------------------------------------------------------------
    Light — the indoor-unit LED ring
    ---------------------------------------------------------------------------
    """

LIGHT_POWER_UNSPECIFIED: LightPower.ValueType  # 0
LIGHT_POWER_ON: LightPower.ValueType  # 1
LIGHT_POWER_OFF: LightPower.ValueType  # 2
Global___LightPower: _TypeAlias = LightPower  # noqa: Y015

class _LightColorPreset:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LightColorPresetEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LightColorPreset.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LIGHT_COLOR_PRESET_UNSPECIFIED: _LightColorPreset.ValueType  # 0
    LIGHT_COLOR_PRESET_DAYLIGHT: _LightColorPreset.ValueType  # 1
    LIGHT_COLOR_PRESET_WARM: _LightColorPreset.ValueType  # 2
    LIGHT_COLOR_PRESET_SUNSET: _LightColorPreset.ValueType  # 3
    LIGHT_COLOR_PRESET_SKY: _LightColorPreset.ValueType  # 4

class LightColorPreset(_LightColorPreset, metaclass=_LightColorPresetEnumTypeWrapper): ...

LIGHT_COLOR_PRESET_UNSPECIFIED: LightColorPreset.ValueType  # 0
LIGHT_COLOR_PRESET_DAYLIGHT: LightColorPreset.ValueType  # 1
LIGHT_COLOR_PRESET_WARM: LightColorPreset.ValueType  # 2
LIGHT_COLOR_PRESET_SUNSET: LightColorPreset.ValueType  # 3
LIGHT_COLOR_PRESET_SKY: LightColorPreset.ValueType  # 4
Global___LightColorPreset: _TypeAlias = LightColorPreset  # noqa: Y015

class _LightAnimation:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LightAnimationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LightAnimation.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LIGHT_ANIMATION_UNSPECIFIED: _LightAnimation.ValueType  # 0
    LIGHT_ANIMATION_NONE: _LightAnimation.ValueType  # 1
    LIGHT_ANIMATION_SPARKLE_FADE: _LightAnimation.ValueType  # 2
    LIGHT_ANIMATION_TWINKLE_FADE: _LightAnimation.ValueType  # 3
    LIGHT_ANIMATION_DANCE: _LightAnimation.ValueType  # 4
    LIGHT_ANIMATION_CHASE: _LightAnimation.ValueType  # 5

class LightAnimation(_LightAnimation, metaclass=_LightAnimationEnumTypeWrapper): ...

LIGHT_ANIMATION_UNSPECIFIED: LightAnimation.ValueType  # 0
LIGHT_ANIMATION_NONE: LightAnimation.ValueType  # 1
LIGHT_ANIMATION_SPARKLE_FADE: LightAnimation.ValueType  # 2
LIGHT_ANIMATION_TWINKLE_FADE: LightAnimation.ValueType  # 3
LIGHT_ANIMATION_DANCE: LightAnimation.ValueType  # 4
LIGHT_ANIMATION_CHASE: LightAnimation.ValueType  # 5
Global___LightAnimation: _TypeAlias = LightAnimation  # noqa: Y015

@_typing.final
class SubmitActionRequest(_message.Message):
    """---------------------------------------------------------------------------
    Request / response
    ---------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_REQUEST_ID_FIELD_NUMBER: _builtins.int
    SYSTEM_ID_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    client_request_id: _builtins.str
    """client-generated idempotency key"""
    system_id: _builtins.str
    @_builtins.property
    def source(self) -> Global___ActionSource:
        """who/what initiated the action"""

    @_builtins.property
    def action(self) -> Global___Action: ...
    def __init__(
        self,
        *,
        client_request_id: _builtins.str | None = ...,
        system_id: _builtins.str | None = ...,
        source: Global___ActionSource | None = ...,
        action: Global___Action | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_client_request_id", b"_client_request_id", "_system_id", b"_system_id", "action", b"action", "client_request_id", b"client_request_id", "source", b"source", "system_id", b"system_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_client_request_id", b"_client_request_id", "_system_id", b"_system_id", "action", b"action", "client_request_id", b"client_request_id", "source", b"source", "system_id", b"system_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__client_request_id: _TypeAlias = _typing.Literal["client_request_id"]  # noqa: Y015
    _WhichOneofArgType__client_request_id: _TypeAlias = _typing.Literal["_client_request_id", b"_client_request_id"]  # noqa: Y015
    _WhichOneofReturnType__system_id: _TypeAlias = _typing.Literal["system_id"]  # noqa: Y015
    _WhichOneofArgType__system_id: _TypeAlias = _typing.Literal["_system_id", b"_system_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__client_request_id) -> _WhichOneofReturnType__client_request_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__system_id) -> _WhichOneofReturnType__system_id | None: ...

Global___SubmitActionRequest: _TypeAlias = SubmitActionRequest  # noqa: Y015

@_typing.final
class SubmitActionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACTION_ID_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    FAILURE_REASON_FIELD_NUMBER: _builtins.int
    action_id: _builtins.str
    result: Global___ActionResult.ValueType
    failure_reason: _builtins.str
    def __init__(
        self,
        *,
        action_id: _builtins.str | None = ...,
        result: Global___ActionResult.ValueType = ...,
        failure_reason: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_action_id", b"_action_id", "_failure_reason", b"_failure_reason", "action_id", b"action_id", "failure_reason", b"failure_reason"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_action_id", b"_action_id", "_failure_reason", b"_failure_reason", "action_id", b"action_id", "failure_reason", b"failure_reason", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__action_id: _TypeAlias = _typing.Literal["action_id"]  # noqa: Y015
    _WhichOneofArgType__action_id: _TypeAlias = _typing.Literal["_action_id", b"_action_id"]  # noqa: Y015
    _WhichOneofReturnType__failure_reason: _TypeAlias = _typing.Literal["failure_reason"]  # noqa: Y015
    _WhichOneofArgType__failure_reason: _TypeAlias = _typing.Literal["_failure_reason", b"_failure_reason"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__action_id) -> _WhichOneofReturnType__action_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__failure_reason) -> _WhichOneofReturnType__failure_reason | None: ...

Global___SubmitActionResponse: _TypeAlias = SubmitActionResponse  # noqa: Y015

@_typing.final
class UserSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    CLIENT_TYPE_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    client_type: Global___ClientType.ValueType
    client_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str | None = ...,
        client_type: Global___ClientType.ValueType = ...,
        client_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_client_id", b"_client_id", "_user_id", b"_user_id", "client_id", b"client_id", "user_id", b"user_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_client_id", b"_client_id", "_user_id", b"_user_id", "client_id", b"client_id", "client_type", b"client_type", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__client_id: _TypeAlias = _typing.Literal["client_id"]  # noqa: Y015
    _WhichOneofArgType__client_id: _TypeAlias = _typing.Literal["_client_id", b"_client_id"]  # noqa: Y015
    _WhichOneofReturnType__user_id: _TypeAlias = _typing.Literal["user_id"]  # noqa: Y015
    _WhichOneofArgType__user_id: _TypeAlias = _typing.Literal["_user_id", b"_user_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__client_id) -> _WhichOneofReturnType__client_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__user_id) -> _WhichOneofReturnType__user_id | None: ...

Global___UserSource: _TypeAlias = UserSource  # noqa: Y015

@_typing.final
class PhysicalSource(_message.Message):
    """A device-originated action — presumably a Dial knob turn or IDU button press (unconfirmed)."""

    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    def __init__(
        self,
        *,
        device_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_device_id", b"_device_id", "device_id", b"device_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_device_id", b"_device_id", "device_id", b"device_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__device_id: _TypeAlias = _typing.Literal["device_id"]  # noqa: Y015
    _WhichOneofArgType__device_id: _TypeAlias = _typing.Literal["_device_id", b"_device_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__device_id) -> _WhichOneofReturnType__device_id | None: ...

Global___PhysicalSource: _TypeAlias = PhysicalSource  # noqa: Y015

@_typing.final
class AutomationSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUTOMATION_ID_FIELD_NUMBER: _builtins.int
    automation_id: _builtins.str
    """HDS Automation object id (tree field 23)"""
    def __init__(
        self,
        *,
        automation_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_automation_id", b"_automation_id", "automation_id", b"automation_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_automation_id", b"_automation_id", "automation_id", b"automation_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__automation_id: _TypeAlias = _typing.Literal["automation_id"]  # noqa: Y015
    _WhichOneofArgType__automation_id: _TypeAlias = _typing.Literal["_automation_id", b"_automation_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__automation_id) -> _WhichOneofReturnType__automation_id | None: ...

Global___AutomationSource: _TypeAlias = AutomationSource  # noqa: Y015

@_typing.final
class PartnerSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARTNER_ID_FIELD_NUMBER: _builtins.int
    partner_id: _builtins.str
    def __init__(
        self,
        *,
        partner_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_partner_id", b"_partner_id", "partner_id", b"partner_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_partner_id", b"_partner_id", "partner_id", b"partner_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__partner_id: _TypeAlias = _typing.Literal["partner_id"]  # noqa: Y015
    _WhichOneofArgType__partner_id: _TypeAlias = _typing.Literal["_partner_id", b"_partner_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__partner_id) -> _WhichOneofReturnType__partner_id | None: ...

Global___PartnerSource: _TypeAlias = PartnerSource  # noqa: Y015

@_typing.final
class CloudSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CloudSource: _TypeAlias = CloudSource  # noqa: Y015

@_typing.final
class ActionSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    PHYSICAL_FIELD_NUMBER: _builtins.int
    AUTOMATION_FIELD_NUMBER: _builtins.int
    PARTNER_FIELD_NUMBER: _builtins.int
    CLOUD_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___UserSource: ...
    @_builtins.property
    def physical(self) -> Global___PhysicalSource: ...
    @_builtins.property
    def automation(self) -> Global___AutomationSource: ...
    @_builtins.property
    def partner(self) -> Global___PartnerSource: ...
    @_builtins.property
    def cloud(self) -> Global___CloudSource: ...
    def __init__(
        self,
        *,
        user: Global___UserSource | None = ...,
        physical: Global___PhysicalSource | None = ...,
        automation: Global___AutomationSource | None = ...,
        partner: Global___PartnerSource | None = ...,
        cloud: Global___CloudSource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["automation", b"automation", "cloud", b"cloud", "partner", b"partner", "physical", b"physical", "source", b"source", "user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["automation", b"automation", "cloud", b"cloud", "partner", b"partner", "physical", b"physical", "source", b"source", "user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_source: _TypeAlias = _typing.Literal["user", "physical", "automation", "partner", "cloud"]  # noqa: Y015
    _WhichOneofArgType_source: _TypeAlias = _typing.Literal["source", b"source"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_source) -> _WhichOneofReturnType_source | None: ...

Global___ActionSource: _TypeAlias = ActionSource  # noqa: Y015

@_typing.final
class Action(_message.Message):
    """---------------------------------------------------------------------------
    Action + targets
    ---------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    CLIMATE_FIELD_NUMBER: _builtins.int
    LIGHT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def climate(self) -> Global___ClimateAction: ...
    @_builtins.property
    def light(self) -> Global___LightAction: ...
    def __init__(
        self,
        *,
        climate: Global___ClimateAction | None = ...,
        light: Global___LightAction | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["category", b"category", "climate", b"climate", "light", b"light"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["category", b"category", "climate", b"climate", "light", b"light"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_category: _TypeAlias = _typing.Literal["climate", "light"]  # noqa: Y015
    _WhichOneofArgType_category: _TypeAlias = _typing.Literal["category", b"category"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_category) -> _WhichOneofReturnType_category | None: ...

Global___Action: _TypeAlias = Action  # noqa: Y015

@_typing.final
class ActionTarget(_message.Message):
    """What an action applies to. Note the field order differs from the Automation
    target (quilt_hds.proto AutomationTarget: ducted_zone=1, space=2, indoor_unit=3),
    and this one adds air_handling_unit and whole-system targets.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SPACE_ID_FIELD_NUMBER: _builtins.int
    DUCTED_ZONE_ID_FIELD_NUMBER: _builtins.int
    INDOOR_UNIT_ID_FIELD_NUMBER: _builtins.int
    AIR_HANDLING_UNIT_ID_FIELD_NUMBER: _builtins.int
    SYSTEM_ID_FIELD_NUMBER: _builtins.int
    space_id: _builtins.str
    ducted_zone_id: _builtins.str
    indoor_unit_id: _builtins.str
    air_handling_unit_id: _builtins.str
    system_id: _builtins.str
    def __init__(
        self,
        *,
        space_id: _builtins.str = ...,
        ducted_zone_id: _builtins.str = ...,
        indoor_unit_id: _builtins.str = ...,
        air_handling_unit_id: _builtins.str = ...,
        system_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["air_handling_unit_id", b"air_handling_unit_id", "ducted_zone_id", b"ducted_zone_id", "indoor_unit_id", b"indoor_unit_id", "kind", b"kind", "space_id", b"space_id", "system_id", b"system_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["air_handling_unit_id", b"air_handling_unit_id", "ducted_zone_id", b"ducted_zone_id", "indoor_unit_id", b"indoor_unit_id", "kind", b"kind", "space_id", b"space_id", "system_id", b"system_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["space_id", "ducted_zone_id", "indoor_unit_id", "air_handling_unit_id", "system_id"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___ActionTarget: _TypeAlias = ActionTarget  # noqa: Y015

@_typing.final
class FanSpeed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LEVEL_FIELD_NUMBER: _builtins.int
    level: Global___FanSpeedLevel.ValueType
    def __init__(
        self,
        *,
        level: Global___FanSpeedLevel.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["level", b"level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FanSpeed: _TypeAlias = FanSpeed  # noqa: Y015

@_typing.final
class FanAngle(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LEVEL_FIELD_NUMBER: _builtins.int
    level: Global___FanAngleLevel.ValueType
    def __init__(
        self,
        *,
        level: Global___FanAngleLevel.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["level", b"level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FanAngle: _TypeAlias = FanAngle  # noqa: Y015

@_typing.final
class SetModeAction(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGETS_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    mode: Global___ClimateMode.ValueType
    @_builtins.property
    def targets(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActionTarget]: ...
    def __init__(
        self,
        *,
        targets: _abc.Iterable[Global___ActionTarget] | None = ...,
        mode: Global___ClimateMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mode", b"mode", "targets", b"targets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetModeAction: _TypeAlias = SetModeAction  # noqa: Y015

@_typing.final
class SetTemperaturesAction(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGETS_FIELD_NUMBER: _builtins.int
    HEAT_SETPOINT_C_FIELD_NUMBER: _builtins.int
    COOL_SETPOINT_C_FIELD_NUMBER: _builtins.int
    heat_setpoint_c: _builtins.float
    cool_setpoint_c: _builtins.float
    @_builtins.property
    def targets(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActionTarget]: ...
    def __init__(
        self,
        *,
        targets: _abc.Iterable[Global___ActionTarget] | None = ...,
        heat_setpoint_c: _builtins.float | None = ...,
        cool_setpoint_c: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_cool_setpoint_c", b"_cool_setpoint_c", "_heat_setpoint_c", b"_heat_setpoint_c", "cool_setpoint_c", b"cool_setpoint_c", "heat_setpoint_c", b"heat_setpoint_c"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_cool_setpoint_c", b"_cool_setpoint_c", "_heat_setpoint_c", b"_heat_setpoint_c", "cool_setpoint_c", b"cool_setpoint_c", "heat_setpoint_c", b"heat_setpoint_c", "targets", b"targets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__cool_setpoint_c: _TypeAlias = _typing.Literal["cool_setpoint_c"]  # noqa: Y015
    _WhichOneofArgType__cool_setpoint_c: _TypeAlias = _typing.Literal["_cool_setpoint_c", b"_cool_setpoint_c"]  # noqa: Y015
    _WhichOneofReturnType__heat_setpoint_c: _TypeAlias = _typing.Literal["heat_setpoint_c"]  # noqa: Y015
    _WhichOneofArgType__heat_setpoint_c: _TypeAlias = _typing.Literal["_heat_setpoint_c", b"_heat_setpoint_c"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__cool_setpoint_c) -> _WhichOneofReturnType__cool_setpoint_c | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__heat_setpoint_c) -> _WhichOneofReturnType__heat_setpoint_c | None: ...

Global___SetTemperaturesAction: _TypeAlias = SetTemperaturesAction  # noqa: Y015

@_typing.final
class SetFanSpeedAction(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGETS_FIELD_NUMBER: _builtins.int
    FAN_SPEED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def targets(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActionTarget]: ...
    @_builtins.property
    def fan_speed(self) -> Global___FanSpeed: ...
    def __init__(
        self,
        *,
        targets: _abc.Iterable[Global___ActionTarget] | None = ...,
        fan_speed: Global___FanSpeed | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fan_speed", b"fan_speed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fan_speed", b"fan_speed", "targets", b"targets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetFanSpeedAction: _TypeAlias = SetFanSpeedAction  # noqa: Y015

@_typing.final
class SetFanAngleAction(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGETS_FIELD_NUMBER: _builtins.int
    FAN_ANGLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def targets(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActionTarget]: ...
    @_builtins.property
    def fan_angle(self) -> Global___FanAngle: ...
    def __init__(
        self,
        *,
        targets: _abc.Iterable[Global___ActionTarget] | None = ...,
        fan_angle: Global___FanAngle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fan_angle", b"fan_angle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fan_angle", b"fan_angle", "targets", b"targets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetFanAngleAction: _TypeAlias = SetFanAngleAction  # noqa: Y015

@_typing.final
class ClimateAction(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SET_MODE_FIELD_NUMBER: _builtins.int
    SET_TEMPERATURES_FIELD_NUMBER: _builtins.int
    SET_FAN_SPEED_FIELD_NUMBER: _builtins.int
    SET_FAN_ANGLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def set_mode(self) -> Global___SetModeAction: ...
    @_builtins.property
    def set_temperatures(self) -> Global___SetTemperaturesAction: ...
    @_builtins.property
    def set_fan_speed(self) -> Global___SetFanSpeedAction: ...
    @_builtins.property
    def set_fan_angle(self) -> Global___SetFanAngleAction: ...
    def __init__(
        self,
        *,
        set_mode: Global___SetModeAction | None = ...,
        set_temperatures: Global___SetTemperaturesAction | None = ...,
        set_fan_speed: Global___SetFanSpeedAction | None = ...,
        set_fan_angle: Global___SetFanAngleAction | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "set_fan_angle", b"set_fan_angle", "set_fan_speed", b"set_fan_speed", "set_mode", b"set_mode", "set_temperatures", b"set_temperatures"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "set_fan_angle", b"set_fan_angle", "set_fan_speed", b"set_fan_speed", "set_mode", b"set_mode", "set_temperatures", b"set_temperatures"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_action: _TypeAlias = _typing.Literal["set_mode", "set_temperatures", "set_fan_speed", "set_fan_angle"]  # noqa: Y015
    _WhichOneofArgType_action: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_action) -> _WhichOneofReturnType_action | None: ...

Global___ClimateAction: _TypeAlias = ClimateAction  # noqa: Y015

@_typing.final
class RgbwColor(_message.Message):
    """Unpacked RGBW, unlike the packed uint32 led_color_code in IndoorUnitControls."""

    DESCRIPTOR: _descriptor.Descriptor

    RED_FIELD_NUMBER: _builtins.int
    GREEN_FIELD_NUMBER: _builtins.int
    BLUE_FIELD_NUMBER: _builtins.int
    WHITE_FIELD_NUMBER: _builtins.int
    red: _builtins.int
    green: _builtins.int
    blue: _builtins.int
    white: _builtins.int
    def __init__(
        self,
        *,
        red: _builtins.int | None = ...,
        green: _builtins.int | None = ...,
        blue: _builtins.int | None = ...,
        white: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_blue", b"_blue", "_green", b"_green", "_red", b"_red", "_white", b"_white", "blue", b"blue", "green", b"green", "red", b"red", "white", b"white"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_blue", b"_blue", "_green", b"_green", "_red", b"_red", "_white", b"_white", "blue", b"blue", "green", b"green", "red", b"red", "white", b"white"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__blue: _TypeAlias = _typing.Literal["blue"]  # noqa: Y015
    _WhichOneofArgType__blue: _TypeAlias = _typing.Literal["_blue", b"_blue"]  # noqa: Y015
    _WhichOneofReturnType__green: _TypeAlias = _typing.Literal["green"]  # noqa: Y015
    _WhichOneofArgType__green: _TypeAlias = _typing.Literal["_green", b"_green"]  # noqa: Y015
    _WhichOneofReturnType__red: _TypeAlias = _typing.Literal["red"]  # noqa: Y015
    _WhichOneofArgType__red: _TypeAlias = _typing.Literal["_red", b"_red"]  # noqa: Y015
    _WhichOneofReturnType__white: _TypeAlias = _typing.Literal["white"]  # noqa: Y015
    _WhichOneofArgType__white: _TypeAlias = _typing.Literal["_white", b"_white"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__blue) -> _WhichOneofReturnType__blue | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__green) -> _WhichOneofReturnType__green | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__red) -> _WhichOneofReturnType__red | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__white) -> _WhichOneofReturnType__white | None: ...

Global___RgbwColor: _TypeAlias = RgbwColor  # noqa: Y015

@_typing.final
class LightColor(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRESET_FIELD_NUMBER: _builtins.int
    CUSTOM_FIELD_NUMBER: _builtins.int
    preset: Global___LightColorPreset.ValueType
    @_builtins.property
    def custom(self) -> Global___RgbwColor: ...
    def __init__(
        self,
        *,
        preset: Global___LightColorPreset.ValueType = ...,
        custom: Global___RgbwColor | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["custom", b"custom", "preset", b"preset", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["custom", b"custom", "preset", b"preset", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["preset", "custom"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___LightColor: _TypeAlias = LightColor  # noqa: Y015

@_typing.final
class LightControls(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POWER_FIELD_NUMBER: _builtins.int
    BRIGHTNESS_PERCENT_FIELD_NUMBER: _builtins.int
    COLOR_FIELD_NUMBER: _builtins.int
    ANIMATION_FIELD_NUMBER: _builtins.int
    power: Global___LightPower.ValueType
    brightness_percent: _builtins.float
    animation: Global___LightAnimation.ValueType
    @_builtins.property
    def color(self) -> Global___LightColor: ...
    def __init__(
        self,
        *,
        power: Global___LightPower.ValueType = ...,
        brightness_percent: _builtins.float | None = ...,
        color: Global___LightColor | None = ...,
        animation: Global___LightAnimation.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_brightness_percent", b"_brightness_percent", "brightness_percent", b"brightness_percent", "color", b"color"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_brightness_percent", b"_brightness_percent", "animation", b"animation", "brightness_percent", b"brightness_percent", "color", b"color", "power", b"power"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__brightness_percent: _TypeAlias = _typing.Literal["brightness_percent"]  # noqa: Y015
    _WhichOneofArgType__brightness_percent: _TypeAlias = _typing.Literal["_brightness_percent", b"_brightness_percent"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__brightness_percent) -> _WhichOneofReturnType__brightness_percent | None: ...

Global___LightControls: _TypeAlias = LightControls  # noqa: Y015

@_typing.final
class SetLightAction(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGETS_FIELD_NUMBER: _builtins.int
    CONTROLS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def targets(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActionTarget]: ...
    @_builtins.property
    def controls(self) -> Global___LightControls: ...
    def __init__(
        self,
        *,
        targets: _abc.Iterable[Global___ActionTarget] | None = ...,
        controls: Global___LightControls | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["controls", b"controls"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["controls", b"controls", "targets", b"targets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetLightAction: _TypeAlias = SetLightAction  # noqa: Y015

@_typing.final
class LightAction(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SET_LIGHT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def set_light(self) -> Global___SetLightAction: ...
    def __init__(
        self,
        *,
        set_light: Global___SetLightAction | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "set_light", b"set_light"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "set_light", b"set_light"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_action: _TypeAlias = _typing.Literal["set_light"]  # noqa: Y015
    _WhichOneofArgType_action: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_action) -> _WhichOneofReturnType_action | None: ...

Global___LightAction: _TypeAlias = LightAction  # noqa: Y015
