# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import quilt_services_pb2 as quilt__services__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quilt_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLoggedInUser = channel.unary_unary(
                '/core.protos.app.UserService/GetLoggedInUser',
                request_serializer=quilt__services__pb2.GetLoggedInUserRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.GetLoggedInUserResponse.FromString,
                _registered_method=True)
        self.UpdateLoggedInUser = channel.unary_unary(
                '/core.protos.app.UserService/UpdateLoggedInUser',
                request_serializer=quilt__services__pb2.UpdateLoggedInUserRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.UpdateLoggedInUserResponse.FromString,
                _registered_method=True)
        self.GetUserAttributes = channel.unary_unary(
                '/core.protos.app.UserService/GetUserAttributes',
                request_serializer=quilt__services__pb2.GetUserAttributesRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.UserAttributes.FromString,
                _registered_method=True)
        self.PatchUserAttributes = channel.unary_unary(
                '/core.protos.app.UserService/PatchUserAttributes',
                request_serializer=quilt__services__pb2.PatchUserAttributesRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.UserAttributes.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLoggedInUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLoggedInUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchUserAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLoggedInUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoggedInUser,
                    request_deserializer=quilt__services__pb2.GetLoggedInUserRequest.FromString,
                    response_serializer=quilt__services__pb2.GetLoggedInUserResponse.SerializeToString,
            ),
            'UpdateLoggedInUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLoggedInUser,
                    request_deserializer=quilt__services__pb2.UpdateLoggedInUserRequest.FromString,
                    response_serializer=quilt__services__pb2.UpdateLoggedInUserResponse.SerializeToString,
            ),
            'GetUserAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAttributes,
                    request_deserializer=quilt__services__pb2.GetUserAttributesRequest.FromString,
                    response_serializer=quilt__services__pb2.UserAttributes.SerializeToString,
            ),
            'PatchUserAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchUserAttributes,
                    request_deserializer=quilt__services__pb2.PatchUserAttributesRequest.FromString,
                    response_serializer=quilt__services__pb2.UserAttributes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.protos.app.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.protos.app.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLoggedInUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.UserService/GetLoggedInUser',
            quilt__services__pb2.GetLoggedInUserRequest.SerializeToString,
            quilt__services__pb2.GetLoggedInUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLoggedInUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.UserService/UpdateLoggedInUser',
            quilt__services__pb2.UpdateLoggedInUserRequest.SerializeToString,
            quilt__services__pb2.UpdateLoggedInUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.UserService/GetUserAttributes',
            quilt__services__pb2.GetUserAttributesRequest.SerializeToString,
            quilt__services__pb2.UserAttributes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchUserAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.UserService/PatchUserAttributes',
            quilt__services__pb2.PatchUserAttributesRequest.SerializeToString,
            quilt__services__pb2.UserAttributes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SystemInformationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSystems = channel.unary_unary(
                '/core.protos.app.SystemInformationService/ListSystems',
                request_serializer=quilt__services__pb2.ListSystemInformationRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.ListSystemInformationResponse.FromString,
                _registered_method=True)
        self.SetAddress = channel.unary_unary(
                '/core.protos.app.SystemInformationService/SetAddress',
                request_serializer=quilt__services__pb2.SetAddressRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.SetAddressResponse.FromString,
                _registered_method=True)
        self.GetEnergyMetrics = channel.unary_unary(
                '/core.protos.app.SystemInformationService/GetEnergyMetrics',
                request_serializer=quilt__services__pb2.GetEnergyMetricsRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.GetEnergyMetricsResponse.FromString,
                _registered_method=True)


class SystemInformationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListSystems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnergyMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemInformationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSystems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSystems,
                    request_deserializer=quilt__services__pb2.ListSystemInformationRequest.FromString,
                    response_serializer=quilt__services__pb2.ListSystemInformationResponse.SerializeToString,
            ),
            'SetAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAddress,
                    request_deserializer=quilt__services__pb2.SetAddressRequest.FromString,
                    response_serializer=quilt__services__pb2.SetAddressResponse.SerializeToString,
            ),
            'GetEnergyMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnergyMetrics,
                    request_deserializer=quilt__services__pb2.GetEnergyMetricsRequest.FromString,
                    response_serializer=quilt__services__pb2.GetEnergyMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.protos.app.SystemInformationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.protos.app.SystemInformationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemInformationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSystems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.SystemInformationService/ListSystems',
            quilt__services__pb2.ListSystemInformationRequest.SerializeToString,
            quilt__services__pb2.ListSystemInformationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.SystemInformationService/SetAddress',
            quilt__services__pb2.SetAddressRequest.SerializeToString,
            quilt__services__pb2.SetAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnergyMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.SystemInformationService/GetEnergyMetrics',
            quilt__services__pb2.GetEnergyMetricsRequest.SerializeToString,
            quilt__services__pb2.GetEnergyMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InvitationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPendingInvitationsForLoggedInUser = channel.unary_unary(
                '/core.protos.app.InvitationService/ListPendingInvitationsForLoggedInUser',
                request_serializer=quilt__services__pb2.ListPendingInvitationsRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.ListPendingInvitationsResponse.FromString,
                _registered_method=True)
        self.CreateInvitation = channel.unary_unary(
                '/core.protos.app.InvitationService/CreateInvitation',
                request_serializer=quilt__services__pb2.CreateInvitationRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.CreateInvitationResponse.FromString,
                _registered_method=True)
        self.AcceptInvitation = channel.unary_unary(
                '/core.protos.app.InvitationService/AcceptInvitation',
                request_serializer=quilt__services__pb2.AcceptInvitationRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.AcceptInvitationResponse.FromString,
                _registered_method=True)
        self.RejectInvitation = channel.unary_unary(
                '/core.protos.app.InvitationService/RejectInvitation',
                request_serializer=quilt__services__pb2.RejectInvitationRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.RejectInvitationResponse.FromString,
                _registered_method=True)
        self.CancelInvitation = channel.unary_unary(
                '/core.protos.app.InvitationService/CancelInvitation',
                request_serializer=quilt__services__pb2.CancelInvitationRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.CancelInvitationResponse.FromString,
                _registered_method=True)
        self.SendNotificationForInvitation = channel.unary_unary(
                '/core.protos.app.InvitationService/SendNotificationForInvitation',
                request_serializer=quilt__services__pb2.SendNotificationForInvitationRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.SendNotificationForInvitationResponse.FromString,
                _registered_method=True)


class InvitationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListPendingInvitationsForLoggedInUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInvitation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptInvitation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectInvitation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelInvitation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNotificationForInvitation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvitationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPendingInvitationsForLoggedInUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPendingInvitationsForLoggedInUser,
                    request_deserializer=quilt__services__pb2.ListPendingInvitationsRequest.FromString,
                    response_serializer=quilt__services__pb2.ListPendingInvitationsResponse.SerializeToString,
            ),
            'CreateInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInvitation,
                    request_deserializer=quilt__services__pb2.CreateInvitationRequest.FromString,
                    response_serializer=quilt__services__pb2.CreateInvitationResponse.SerializeToString,
            ),
            'AcceptInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptInvitation,
                    request_deserializer=quilt__services__pb2.AcceptInvitationRequest.FromString,
                    response_serializer=quilt__services__pb2.AcceptInvitationResponse.SerializeToString,
            ),
            'RejectInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectInvitation,
                    request_deserializer=quilt__services__pb2.RejectInvitationRequest.FromString,
                    response_serializer=quilt__services__pb2.RejectInvitationResponse.SerializeToString,
            ),
            'CancelInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelInvitation,
                    request_deserializer=quilt__services__pb2.CancelInvitationRequest.FromString,
                    response_serializer=quilt__services__pb2.CancelInvitationResponse.SerializeToString,
            ),
            'SendNotificationForInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotificationForInvitation,
                    request_deserializer=quilt__services__pb2.SendNotificationForInvitationRequest.FromString,
                    response_serializer=quilt__services__pb2.SendNotificationForInvitationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.protos.app.InvitationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.protos.app.InvitationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InvitationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPendingInvitationsForLoggedInUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.InvitationService/ListPendingInvitationsForLoggedInUser',
            quilt__services__pb2.ListPendingInvitationsRequest.SerializeToString,
            quilt__services__pb2.ListPendingInvitationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.InvitationService/CreateInvitation',
            quilt__services__pb2.CreateInvitationRequest.SerializeToString,
            quilt__services__pb2.CreateInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.InvitationService/AcceptInvitation',
            quilt__services__pb2.AcceptInvitationRequest.SerializeToString,
            quilt__services__pb2.AcceptInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.InvitationService/RejectInvitation',
            quilt__services__pb2.RejectInvitationRequest.SerializeToString,
            quilt__services__pb2.RejectInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.InvitationService/CancelInvitation',
            quilt__services__pb2.CancelInvitationRequest.SerializeToString,
            quilt__services__pb2.CancelInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendNotificationForInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.InvitationService/SendNotificationForInvitation',
            quilt__services__pb2.SendNotificationForInvitationRequest.SerializeToString,
            quilt__services__pb2.SendNotificationForInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PartnerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InviteSystemOwner = channel.unary_unary(
                '/core.protos.app.PartnerService/InviteSystemOwner',
                request_serializer=quilt__services__pb2.InviteSystemOwnerRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.InviteSystemOwnerResponse.FromString,
                _registered_method=True)
        self.GetLoggedInUserPartnerDetails = channel.unary_unary(
                '/core.protos.app.PartnerService/GetLoggedInUserPartnerDetails',
                request_serializer=quilt__services__pb2.GetLoggedInUserPartnerDetailsRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.GetLoggedInUserPartnerDetailsResponse.FromString,
                _registered_method=True)
        self.JoinPartnerOrganization = channel.unary_unary(
                '/core.protos.app.PartnerService/JoinPartnerOrganization',
                request_serializer=quilt__services__pb2.JoinPartnerOrganizationRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.JoinPartnerOrganizationResponse.FromString,
                _registered_method=True)
        self.LeavePartnerOrganization = channel.unary_unary(
                '/core.protos.app.PartnerService/LeavePartnerOrganization',
                request_serializer=quilt__services__pb2.LeavePartnerOrganizationRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.LeavePartnerOrganizationResponse.FromString,
                _registered_method=True)


class PartnerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InviteSystemOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoggedInUserPartnerDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinPartnerOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeavePartnerOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InviteSystemOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteSystemOwner,
                    request_deserializer=quilt__services__pb2.InviteSystemOwnerRequest.FromString,
                    response_serializer=quilt__services__pb2.InviteSystemOwnerResponse.SerializeToString,
            ),
            'GetLoggedInUserPartnerDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoggedInUserPartnerDetails,
                    request_deserializer=quilt__services__pb2.GetLoggedInUserPartnerDetailsRequest.FromString,
                    response_serializer=quilt__services__pb2.GetLoggedInUserPartnerDetailsResponse.SerializeToString,
            ),
            'JoinPartnerOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinPartnerOrganization,
                    request_deserializer=quilt__services__pb2.JoinPartnerOrganizationRequest.FromString,
                    response_serializer=quilt__services__pb2.JoinPartnerOrganizationResponse.SerializeToString,
            ),
            'LeavePartnerOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.LeavePartnerOrganization,
                    request_deserializer=quilt__services__pb2.LeavePartnerOrganizationRequest.FromString,
                    response_serializer=quilt__services__pb2.LeavePartnerOrganizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.protos.app.PartnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.protos.app.PartnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PartnerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InviteSystemOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.PartnerService/InviteSystemOwner',
            quilt__services__pb2.InviteSystemOwnerRequest.SerializeToString,
            quilt__services__pb2.InviteSystemOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoggedInUserPartnerDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.PartnerService/GetLoggedInUserPartnerDetails',
            quilt__services__pb2.GetLoggedInUserPartnerDetailsRequest.SerializeToString,
            quilt__services__pb2.GetLoggedInUserPartnerDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinPartnerOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.PartnerService/JoinPartnerOrganization',
            quilt__services__pb2.JoinPartnerOrganizationRequest.SerializeToString,
            quilt__services__pb2.JoinPartnerOrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeavePartnerOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.PartnerService/LeavePartnerOrganization',
            quilt__services__pb2.LeavePartnerOrganizationRequest.SerializeToString,
            quilt__services__pb2.LeavePartnerOrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SystemUserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSystemUsers = channel.unary_unary(
                '/core.protos.app.SystemUserService/ListSystemUsers',
                request_serializer=quilt__services__pb2.ListSystemUsersRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.ListSystemUsersResponse.FromString,
                _registered_method=True)
        self.GetRoleOfLoggedInSystemUser = channel.unary_unary(
                '/core.protos.app.SystemUserService/GetRoleOfLoggedInSystemUser',
                request_serializer=quilt__services__pb2.GetRoleOfLoggedInSystemUserRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.GetRoleOfLoggedInSystemUserResponse.FromString,
                _registered_method=True)
        self.RemoveSystemUser = channel.unary_unary(
                '/core.protos.app.SystemUserService/RemoveSystemUser',
                request_serializer=quilt__services__pb2.RemoveSystemUserRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.RemoveSystemUserResponse.FromString,
                _registered_method=True)
        self.RemoveLoggedInSystemUser = channel.unary_unary(
                '/core.protos.app.SystemUserService/RemoveLoggedInSystemUser',
                request_serializer=quilt__services__pb2.RemoveLoggedInSystemUserRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.RemoveLoggedInSystemUserResponse.FromString,
                _registered_method=True)
        self.ChangeRoleOfSystemUser = channel.unary_unary(
                '/core.protos.app.SystemUserService/ChangeRoleOfSystemUser',
                request_serializer=quilt__services__pb2.ChangeRoleOfSystemUserRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.ChangeRoleOfSystemUserResponse.FromString,
                _registered_method=True)


class SystemUserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListSystemUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoleOfLoggedInSystemUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSystemUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveLoggedInSystemUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeRoleOfSystemUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemUserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSystemUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSystemUsers,
                    request_deserializer=quilt__services__pb2.ListSystemUsersRequest.FromString,
                    response_serializer=quilt__services__pb2.ListSystemUsersResponse.SerializeToString,
            ),
            'GetRoleOfLoggedInSystemUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoleOfLoggedInSystemUser,
                    request_deserializer=quilt__services__pb2.GetRoleOfLoggedInSystemUserRequest.FromString,
                    response_serializer=quilt__services__pb2.GetRoleOfLoggedInSystemUserResponse.SerializeToString,
            ),
            'RemoveSystemUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSystemUser,
                    request_deserializer=quilt__services__pb2.RemoveSystemUserRequest.FromString,
                    response_serializer=quilt__services__pb2.RemoveSystemUserResponse.SerializeToString,
            ),
            'RemoveLoggedInSystemUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveLoggedInSystemUser,
                    request_deserializer=quilt__services__pb2.RemoveLoggedInSystemUserRequest.FromString,
                    response_serializer=quilt__services__pb2.RemoveLoggedInSystemUserResponse.SerializeToString,
            ),
            'ChangeRoleOfSystemUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeRoleOfSystemUser,
                    request_deserializer=quilt__services__pb2.ChangeRoleOfSystemUserRequest.FromString,
                    response_serializer=quilt__services__pb2.ChangeRoleOfSystemUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.protos.app.SystemUserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.protos.app.SystemUserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemUserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSystemUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.SystemUserService/ListSystemUsers',
            quilt__services__pb2.ListSystemUsersRequest.SerializeToString,
            quilt__services__pb2.ListSystemUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoleOfLoggedInSystemUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.SystemUserService/GetRoleOfLoggedInSystemUser',
            quilt__services__pb2.GetRoleOfLoggedInSystemUserRequest.SerializeToString,
            quilt__services__pb2.GetRoleOfLoggedInSystemUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSystemUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.SystemUserService/RemoveSystemUser',
            quilt__services__pb2.RemoveSystemUserRequest.SerializeToString,
            quilt__services__pb2.RemoveSystemUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveLoggedInSystemUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.SystemUserService/RemoveLoggedInSystemUser',
            quilt__services__pb2.RemoveLoggedInSystemUserRequest.SerializeToString,
            quilt__services__pb2.RemoveLoggedInSystemUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeRoleOfSystemUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.SystemUserService/ChangeRoleOfSystemUser',
            quilt__services__pb2.ChangeRoleOfSystemUserRequest.SerializeToString,
            quilt__services__pb2.ChangeRoleOfSystemUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MobileAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthorizeNewDevice = channel.unary_unary(
                '/core.protos.app.MobileAppService/AuthorizeNewDevice',
                request_serializer=quilt__services__pb2.AuthorizeNewDeviceRequest.SerializeToString,
                response_deserializer=quilt__services__pb2.AuthorizeNewDeviceResponse.FromString,
                _registered_method=True)


class MobileAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuthorizeNewDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobileAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthorizeNewDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeNewDevice,
                    request_deserializer=quilt__services__pb2.AuthorizeNewDeviceRequest.FromString,
                    response_serializer=quilt__services__pb2.AuthorizeNewDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.protos.app.MobileAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.protos.app.MobileAppService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MobileAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthorizeNewDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.app.MobileAppService/AuthorizeNewDevice',
            quilt__services__pb2.AuthorizeNewDeviceRequest.SerializeToString,
            quilt__services__pb2.AuthorizeNewDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
